---

- name: Configure basic settings
  become: yes
  hosts: routers
  gather_facts: False
  tasks:
    
    - name: Backup router
      ios_config:
        backup: yes

    - name: Set hostname to inventory hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}
    
    - name: Set password encryption
      ios_config:
        lines: 
          - service password-encryption

    - name: Set interface ip
      ios_config:
        parents: "interface GigabitEthernet1"
        lines:
          - ip address {{ GI1_ip }} {{ GI1_subnetmask }}

    - name: Set interface ip
      ios_config:
        parents: "interface GigabitEthernet2"
        lines:
          - ip address {{ GI2_ip }} {{ GI2_subnetmask }}

    - name: Set router ospf priority
      ios_config:
        parents: "interface GigabitEthernet1"
        lines:
          - ospf priority {{ ospf_priority }}

    - name: Configure ospf 
      ios_config:
        parents: "router ospf 1"
        lines:
          - network {{ GI1_network }}  {{ GI1_subnetmask }} area 0
          - network {{ GI2_network }}  {{ GI2_subnetmask }} area 0

    - name: dhcp pool lan
      ios_config:
        parents: "ip dhcp pool lan"
        lines:
          - network {{ GI1_network }}
          - default-router {{ GI1_ip }}
          - dns-server 1.1.1.1
          - domain-name baron.intern
    
    - name: Create new user with privilege 15
      ios_config:
        lines:
          - username rykle privilege 15 secret Welkom01!
